# Step 0. Define default env variables
ARG DEFAULT_APP_HOME="/home/www/rails-app"
ARG DEFAULT_GEM_HOME="/usr/local/bundle"
ARG PATH=$GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH

# Layer 1. Download base ruby image.
FROM ruby:3.2.3

# Later 2. Set maintainer
LABEL maintainer="kotchuruba@gmail.com"

# Layer 3. Install curl with recommends
RUN apt update && apt install -y curl

# Layer 4. Copy aptfile to install apt deps
WORKDIR /home
COPY aptfile aptfile

# Layer 5. Updating and installing the necessary software for the Web server. Cleaning to reduce image size.
RUN apt-get update -qq && xargs apt-get install --no-install-recommends -yq < aptfile && export DEBIAN_FRONTEND=noninteractive \
  && apt-get clean && apt-get autoclean && apt-get clean all \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log \
  && rm aptfile
  
# Layer 6. Inherit default variabels
ARG PATH=$GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH
ARG DEFAULT_APP_HOME
ENV APP_HOME=${DEFAULT_APP_HOME}
ENV LANG C.UTF-8

# Layer 7. Install needed version of bundler 
# RUN gem install bundler -v 2.3.26 
RUN gem install bundler
 
# Layer 8. Adding config options for bundler.
RUN echo "gem: --no-rdoc --no-ri" > /etc/gemrc

# Layer 9. Creating and specifying the directory in which the application will be placed.
WORKDIR $APP_HOME

# Layer 10. Copying Gemfile, Gemfile.lock and all .json files.
COPY *.json ./
COPY Gemfile* ./

# Layer 11. Installing dependencies.
RUN bundle check | bundle install --jobs 10

# Layer 12. Copying full application.
COPY . .

# Layer 13. Command to run application.
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]  